#pragma once

#ifndef DIMENSION_H
#define DIMENSION_H



#define UNITY_TILE		35
#define	UNITY_ROBOT		(UNITY_TILE/2.0)
#define UNITY_VECTOR	(UNITY_TILE)
#define	UNITY_VECTOR_HEAD	(UNITY_TILE/5.0)

#define	UNITY_FONT_SPACE	20
#define	UNITY_FONT_LETTER	 (UNITY_FONT_SPACE/2.0)

#define	VECTOR_THICKNESS (UNITY_TILE/20.0)	//<=0

#define OFFSET_HISTOGRAM 8
#define FONT_SIZE_HISTOGRAM ((OFFSET_HISTOGRAM * 3)/2)


#define FONT_SIZE_AXIS	(FONT_SIZE_HISTOGRAM)

#define OFFSET_AXIS (0.09)
#define OFFSET_AXIS_INDICATOR 3
#define SEPARATION_AXIS_Y 4

#define THICKNESS_AXIS 1.0



#endif // DIMENSION_H
