#pragma once

#ifndef DIMENSION_H
#define DIMENSION_H

#define UNITY_TILE		70
#define	UNITY_ROBOT		(UNITY_TILE/2.0)
#define UNITY_VECTOR	(UNITY_TILE)
#define	UNITY_VECTOR_HEAD	(UNITY_TILE/5.0)

#define	UNITY_FONT_SPACE	8.0
#define	UNITY_FONT_LETTER	 (UNITY_FONT_SPACE/3.0)

#define	VECTOR_THICKNESS (UNITY_TILE/20.0)	//<=0


#endif // DIMENSION_H
